import = [
    "~/.config/alacritty/colorscheme.toml",
    "~/.config/alacritty/keybindings.toml",
]

[window]
dimensions = { columns = 100, lines = 44 }
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.65
blur = true
startup_mode = "Windowed"
title = "@tlh"

[scrolling]
history = 100000
multiplier = 4

[font]
size = 11.25
[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "BoldItalic"
[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

