import = [
    # colorscheme
    "~/.config/alacritty/everforest.toml",

    # keybindings
    "~/.config/alacritty/keybindings.toml",
]

[window]
dimensions = { columns = 100, lines = 45 }
padding = { x = 0, y = 0 }
decorations = "None"
opacity = 0.90
blur = true
startup_mode = "Windowed"
title = "@tlh"

[scrolling]
history = 100000
multiplier = 4

[font]
size = 11.25
[font.bold]
family = "Hack Nerd Font"
style = "Bold"
[font.bold_italic]
family = "Hack Nerd Font"
style = "BoldItalic"
[font.italic]
family = "Hack Nerd Font"
style = "Italic"
[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
program = "/usr/bin/tmux"
